DROP DATABASE IF EXISTS SynthDB

CREATE DATABASE SynthDB

DROP TABLE IF EXISTS Sounds
DROP TABLE IF EXISTS Melodies

CREATE TABLE Sounds(
	SoundId INT NOT NULL IDENTITY PRIMARY KEY,
	CharInput VARCHAR(5) NULL,
	Frequency INT NULL,
	SignalType INT NULL
)

INSERT INTO Sounds VALUES ('q', 10, 6)
INSERT INTO Sounds VALUES ('a', 50, 6)
INSERT INTO Sounds VALUES ('z', 100, 6)
INSERT INTO Sounds VALUES ('w', 200, 6)
INSERT INTO Sounds VALUES ('s', 300, 6)
INSERT INTO Sounds VALUES ('x', 400, 6)

INSERT INTO Sounds VALUES ('e', 10, 3)
INSERT INTO Sounds VALUES ('d', 50, 3)
INSERT INTO Sounds VALUES ('c', 100, 3)
INSERT INTO Sounds VALUES ('r', 200, 3)
INSERT INTO Sounds VALUES ('f', 300, 3)
INSERT INTO Sounds VALUES ('v', 400, 3)

INSERT INTO Sounds VALUES ('t', 10, 4)
INSERT INTO Sounds VALUES ('g', 50, 4)
INSERT INTO Sounds VALUES ('b', 100, 4)
INSERT INTO Sounds VALUES ('y', 200, 4)
INSERT INTO Sounds VALUES ('h', 300, 4)
INSERT INTO Sounds VALUES ('n', 400, 4)

INSERT INTO Sounds VALUES ('u', 10, 2)
INSERT INTO Sounds VALUES ('j', 50, 2)
INSERT INTO Sounds VALUES ('m', 100, 2)
INSERT INTO Sounds VALUES ('i', 200, 2)
INSERT INTO Sounds VALUES ('k', 300, 2)
INSERT INTO Sounds VALUES (',', 400, 2)

INSERT INTO Sounds VALUES ('o', 10, 5)
INSERT INTO Sounds VALUES ('l', 50, 5)
INSERT INTO Sounds VALUES ('.', 100, 5)
INSERT INTO Sounds VALUES ('p', 200, 5)
INSERT INTO Sounds VALUES (';', 300, 5)
INSERT INTO Sounds VALUES ('/', 400, 5)

CREATE TABLE Melodies(
	MelodieId INT NOT NULL IDENTITY PRIMARY KEY,
	CharMelodie VARCHAR(200) NULL
)

SELECT * FROM Sounds

SELECT * FROM Melodies